base: &base
  adapter: sqlite3
  timeout: 5000
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  database: db/development.sqlite3
  <<: *base

test:
  database: db/test.sqlite3
  <<: *base

production:
  adapter: postgresql
  database: <%= ENV['PWPUSH_DB_NAME'] %>
  username: <%= ENV['PWPUSH_DB_USERNAME'] %>
  password: <%= ENV['PWPUSH_DB_PASSWORD'] %>
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false
